spring:
  # 启用默认静态资源处理,开启缓存
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        # 缓存响应时间
        max-age: 3600
    chain:
      # 资源链启动缓存,默认启动
      cache: true
      # 启用资源连,默认禁用
      enabled: true
      # 压缩资源(gzip), 默认禁用
      compressed: true
      # 开启h5的应用缓存
      html-application-cache: true
    static-locations: classpath:/static/
  # thymeleaf配置
  thymeleaf:
    cache: false
  # redis配置
  redis:
    host: 106.13.229.77
    port: 6399
    password: redis6399
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数, 默认8
        max-active: 8
        # 最大连接阻塞等待时间, 默认-1
        max-wait: 10000ms
        # 最小空闲连接
        max-idle: 200
        # 最大空闲连接
        min-idle: 5

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: pwd3Y#fLiQM0m_+
    # 数据库连接池
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最大连接数
      minimum-idle: 5
      # 空闲连接最大存活时间,默认10分钟(600000)
      idle-timeout: 180000
      # 最大连接数, 默认数10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间, 0表示永久存活, 默认1800000(30分钟)
      max-lifetime: 180000
      # 连接超时时间, 默认30秒
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1


# mybatis-plus配置
mybatis-plus:
  # 配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 返回的类型别名, 即给实体类起别名
  type-aliases-package: com.chenhf.pojo

# Mybatis  SQL打印(方法接口所在的包, 不是Mapper.xml所在的包)
logging:
  level:
    com.chenhf.mapper: debug
server:
  port: 8080